name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Etiqueta h1
      id: etiqueta-h1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Etiqueta h1
        setup-command: ''
        command: grep -i "<h1>" index.html
        timeout: 10
        max-score: 5
    - name: Etiqueta ul
      id: etiqueta-ul
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Etiqueta ul
        setup-command: ''
        command: grep -i "<ul>" index.html
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ETIQUETA-H1_RESULTS: "${{steps.etiqueta-h1.outputs.result}}"
        ETIQUETA-UL_RESULTS: "${{steps.etiqueta-ul.outputs.result}}"
      with:
        runners: etiqueta-h1,etiqueta-ul
